### ISSUE TITLE
node_color and node_marker only accept Symbol

### ISSUE THREAD

**Issue by babaq** [MakieOrg/GraphMakie.jl#132]
It seems not possible to use arbitrary colors such as RGB, HSL in ColorTypes, and Polygon, BezierPath to customize node shape.

**Comment by babaq** [comment]
just found that it needs to set in the `graphplot` function, using the `p.node_color` will not work.

**Comment by asinghvi17** [comment]
This looks like some Observable type is set prematurely.  Could you post the full error?  It would help us get an idea of how this could be fixed.

**Comment by babaq** [comment]
```julia
using CairoMakie,GraphMakie,Graphs

g = wheel_graph(10)
f, ax, p = graphplot(g)
hidedecorations!(ax); hidespines!(ax)
ax.aspect = DataAspect()
p.node_color=RGBAf(0,0,1,1)
```

ERROR: MethodError: Cannot `convert` an object of type RGBA{Float32} to an object of type Symbol

Closest candidates are:
  convert(::Type{T}, ::T) where T
   @ Base Base.jl:64
  convert(::Type{F}, ::F, ::BlackBoxOptim.FitnessScheme{F}) where F
   @ BlackBoxOptim C:\Users\fff00\.julia\packages\BlackBoxOptim\I3lfp\src\fitness.jl:26
  Symbol(::Any...)
   @ Base strings\basic.jl:229

Stacktrace:
  [1] setproperty!(x::Observable{Symbol}, f::Symbol, v::RGBA{Float32})
    @ Base .\Base.jl:38
  [2] setindex!(observable::Observable, val::Any)
    @ Observables C:\Users\fff00\.julia\packages\Observables\PHGQ8\src\Observables.jl:85
  [3] (::Observables.MapCallback)(value::Any)
    @ Observables C:\Users\fff00\.julia\packages\Observables\PHGQ8\src\Observables.jl:431
  [4] #invokelatest#2
    @ .\essentials.jl:816 [inlined]
  [5] invokelatest
    @ .\essentials.jl:813 [inlined]
  [6] notify
    @ C:\Users\fff00\.julia\packages\Observables\PHGQ8\src\Observables.jl:169 [inlined]
  [7] setindex!(observable::Observable, val::Any)
    @ Observables C:\Users\fff00\.julia\packages\Observables\PHGQ8\src\Observables.jl:86
  [8] setindex!(x::Combined{GraphMakie.graphplot, Tuple{SimpleGraph{Int64}}}, value::RGBA{Float32}, key::Symbol)
    @ MakieCore C:\Users\fff00\.julia\packages\MakieCore\6sckc\src\attributes.jl:209
  [9] setproperty!(x::Combined{GraphMakie.graphplot, Tuple{SimpleGraph{Int64}}}, key::Symbol, value::RGBA{Float32})
    @ MakieCore C:\Users\fff00\.julia\packages\MakieCore\6sckc\src\attributes.jl:86
 [10] top-level scope
    @ c:\Users\fff00\Code\CircuitEstimation.jl:160

i am using Julia v1.9.1 on Win10
 CairoMakie v0.10.6, GraphMakie v0.5.4, Graphs v1.8.0

**Comment by hexaeder** [comment]
Yeah this is a problem with the types. If you don't set `node_color` in the `graphplot` command, it'll be initialized with `:automatic`. Later one, you cannot change an observable of type
```
p.node_color::Observable{Symbol}
```
to `Observable{RGBA{Float32}}`. If you want to change it later you need to prepare the observable with the correct types. For example
```
f,ax,p = graphplot(g; node_color=[RGBA(0,0,0,0) for _ in 1:3])
p.node_color[][1] = RGBA(1,0,0,0)
```
to change the color of the first node of a 3 node graph.

**Comment by hexaeder** [comment]
Feel free to ask further questions here but I'll close the issue since it is like that everywhere in Makie.
