### ISSUE TITLE
Deleting a plot doesn't  remove all listeners

### ISSUE THREAD

**Issue by sents** [MakieOrg/GraphMakie.jl#137]
I've run into an issue when deleting a graph plot from an axis and then mutating the graph.
The issue appears when interacting with the figure after mutating the graph even after the plot was removed.
In the example I replaced the panning of the plot with sending a signal to projectionview.

```julia
using Graphs, GLMakie, GraphMakie
g = wheel_graph(10)

fig = Figure()
ax = Axis(fig[1,1])

p=graphplot!(ax, g)

delete!(ax, p)
rem_edge!(g, 1, 2)

ax.scene.camera.projectionview[] = ax.scene.camera.projectionview.val # Simlulate panning the screen
```
Indeed we can see where the callback originates:
```julia
julia> ax.scene.camera.projectionview
Observable(Float32[0.43081772 0.0 0.0 -0.029146394; 0.0 0.33746386 0.0 0.22875069; 0.0 0.0 -0.0001 0.0; 0.0 0.0 0.0 1.0])
    0 => map((::GraphMakie.var"#21#46")(pxa, pv) @ GraphMakie ~/.julia/packages/GraphMakie/O5CFQ/src/recipes.jl:227)
    0 => map((::GLMakie.var"#190#197")(space, mspace, ::Any, ::Any) @ GLMakie ~/.julia/packages/GLMakie/OVxAi/src/drawing_primitives.jl:211)
    0 => map((::GLMakie.var"#190#197")(space, mspace, ::Any, ::Any) @ GLMakie ~/.julia/packages/GLMakie/OVxAi/src/drawing_primitives.jl:211)
```
The first listener is set in the definition of `plot!(gp::Graphplot)`:
```julia
function Makie.plot!(gp:GraphPlot)
    ...
    # function which projects the point in px space
    to_px = lift(sc.px_area, sc.camera.projectionview) do pxa, pv
        # project should transform to 2d point in px space
        (point) -> project(sc, point)
    end
    ...
```

At some later point in the causality chain we get an error because an edge is missing.
Deleting the plot calls `free` on the plot, which should deregister every callback to the plot object.
Maybe there is some intermediary Observable that fails.

**Comment by hexaeder** [comment]
Do you happen to know of any recipes where the `free` method is overloaded? This is certainly not good and should be fixed, but I am not quite sure how. Because the `to_px` observable is used in different places within the recipe but is not accessible through the `GraphPlot` object itself.

**Comment by SimonDanisch** [comment]
You can do:

  to_px = lift(**gp**, sc.px_area, sc.camera.projectionview) do pxa, pv
      # project should transform to 2d point in px space
      (point) -> project(sc, point)
  end
