### ISSUE TITLE
arrow_shift = :end works poorly with larger edge width

### ISSUE THREAD

**Issue by fredcallaway** [MakieOrg/GraphMakie.jl#171]
Here's an example with edge width 4.

![0125-11073728-problem](https://github.com/MakieOrg/GraphMakie.jl/assets/7883156/1dcec1ed-ef6a-4439-9c4f-1d93479460cc)

Automatically handling this is probably too much to ask. But perhaps we could have an argument that allowed us to fine-tune the positions starting with `arrow_shift = :end`? I think the correct way to handle this would be to simply move the end point of the arrow by some fixed pixel value, (I don't think it should scale with the radius of the destination node).

**Comment by hexaeder** [comment]
Do you mean the problem that the arrow is not really pointy anymore? Unfortunately that cannot be fixed by moving the arrowhead, as the underlying thick edge is drawn all the way to the center of the node position (as can be seen by choosing a transparent node Color, really ugly!). So we'd need to define new endpoints for the "edge lines", which do not coincide with the node position...

**Comment by fredcallaway** [comment]
If you move the arrows, they're not actually pointy, but it looks like a pointy is just behind the state, which to my eye is aesthetically fine. 

But I agree that the best fix would be to move the endpoints for the edge lines. Shouldn't it be pretty straightforward to move the endpoint to wherever the arrow ends up when using `arrow_shift = :end`? I'd be happy to work on a PR if you're open to it.

**Comment by fredcallaway** [comment]
While I'm at it, maybe we should set the default endpoint to the edge of circle to allow for transparent nodes?

**Comment by hexaeder** [comment]
Yes, internally the `:end` option actually updates the `arrow_shift` observable to move the arrow along the line where 0 is the position of the src and 1 the position of the destination node (see `update_arrow_shift` function). The same observable could be used to calculate the line's endpoint in case of `arrow_shift==:end`.

> While I'm at it, maybe we should set the default endpoint to the edge of circle to allow for transparent nodes?

That would be great! Unfortunatley, curvy lines, potential 3d plots, different node shapes and different canvases (dataspace vs. pixelspace) make it quite complex to calculate the intersection between node "surface" and edge path in general. @hdavid16 put quite some effort into the `:end` option for which he needed to calculate the same thing. He might have some insights on that!

**Comment by fredcallaway** [comment]
OK so it sounds like there's interest in a PR. I will first look into whether it's possible to straightforwardly apply the existing code for arrow positioning to also position the end of the line. I'll test curvy and straight lines, but I think I'll restrict myself to 2d (also true for the current `:end` option I think).

**Comment by hdavid16** [comment]
The main code that calculates the edge of the destination node to land the arrowhead on its surface is:
https://github.com/MakieOrg/GraphMakie.jl/blob/804da2dc88c8508d9e17cfbdb4f4d388741649b5/src/recipes.jl#L747-L781

You should be able to calculate the new endpoint for the edge in a similar fashion. However, note that this get's complicated with non-circular nodes: https://github.com/MakieOrg/GraphMakie.jl/issues/115
