### ISSUE TITLE
`pick` one `LineSegments` returns odd index

### ISSUE THREAD

**Issue by hexaeder** [MakieOrg/GraphMakie.jl#175]
> Ah, I unfortunately don't have a very clean MWE - but it is at least relatively short. 
>```jl
>using Pkg
>Pkg.add(["Crystalline", "GLMakie", "GraphMakie"])
>using Crystalline, GLMakie, GraphMakie
>
>gr = maximal_subgroups(210)
>plot(gr)
>```
>which will produce a plot like this:
> <img src="https://github.com/MakieOrg/GraphMakie.jl/assets/26799210/8415dfb6-e398-4f41-96db-0cb6eb4425c3" alt="subgraphs of group #210" width="500"/>
>
>Now, the issue (which only appears to happen on Ubuntu (run through WSL-2), not on plain Windows; I only realized this now):
>
>On mouse-over of the edges or vertices, certain additional information will be displayed. On Ubuntu, the effect occurs, but it is accompanied by a large number of error read-outs with entries like `InexactError: Int64(2.5)`.
>
>Did you want me to open this as a separate issue or is it too vague?

_Originally posted by @thchr in https://github.com/MakieOrg/GraphMakie.jl/issues/166#issuecomment-2010535852_

Unfortunately, I was not able to reproduce locally on MacOS. @thchr can you please try the following MWE in your environment (windows+wsl I guess), move the cursor around in the graph, hover the `LineSegments` and tell me if you encounter any odd indices? If you do so, can you tell me where your cursor was located then?

```julia
using Pkg
pkg"activate --temp"
pkg"add Makie, GLMakie"

using Makie, GLMakie

fig, ax, p = linesegments(Point2[(0,1),(1,1), (0,0), (1,0)], linewidth=10)

interaction = function (event, parent)
    if event.type === MouseEventTypes.over
        obj, idx = pick(parent.scene)
        if obj isa LineSegments
            @info "Interaction with Linesegments" idx
            if isodd(idx)
                @warn "Found odd index!"
            end
        end
    end
end

register_interaction!(ax, :testhover, interaction)
```

I would expect, that the upper line always reports `idx=2` while the lower line reports `idx=4`. Maybe that's not the case for all environments.

Maybe replacing

https://github.com/MakieOrg/GraphMakie.jl/blob/543cc34f391e7de40658ed6c367037ca4e087392/src/interaction.jl#L20

by 
```jl
 return (element.parent, ceil(Int, idx / 2)) 
 ```
 is all that's needed...

**Comment by thchr** [comment]
Thanks for looking at this @hexaeder. I tried out the MWE above on WSL. It seems it does indeed give 1 and 3 as indices:
![image](https://github.com/MakieOrg/GraphMakie.jl/assets/26799210/581d1b25-4874-453c-a1ea-d6bcd68825f7)

**Comment by thchr** [comment]
To be more precise: the top edge gives `idx = 1` or `idx = 2` - it varies (and quickly!). Similarly, the bottom one gives `idx = 3` or `idx = 4`.
