### ISSUE TITLE
Failure to remove edges when updating observable to graph with no edges

### ISSUE THREAD

**Issue by piever** [MakieOrg/GraphMakie.jl#42]
Thanks for this really nice package!

I'm having some issues with the updateability. I'm calling `graphplot(g::Observable{SimpleDiGraph})` and I've noticed that when `g` changes to a graph with no edges, the recipe does not remove the extra edges automatically (or rather, it does, but I need to refresh the page to see the update).

MWE:

```julia
using Graphs, GraphMakie, WGLMakie
g = Observable(complete_digraph(10))
graphplot(g) # graph is rendered correctly
g[] = complete_digraph(5) # graph updates correctly
g[] = SimpleDiGraph(5) # graph with no edges: edges are not removed unless I refresh the page
```

**Comment by hexaeder** [comment]
Interesting :D The code works as expected in `GLMakie`. I think this is a problem with `WGLMakie` rather than `GraphMakie`

```julia
using WGLMakie
a = Observable(rand(Point2, 5))
scatter(a)
a[] = rand(Point2, 2) # works
a[] = rand(Point2, 0) # does not work until update
```

**Comment by hexaeder** [comment]
fixed in Makie :)
