### ISSUE TITLE
Changing nlabels does not update the plot

### ISSUE THREAD

**Issue by diegozea** [MakieOrg/GraphMakie.jl#66]
Hi!

I was trying to show and hide labels using click events, but I notice that doing `plt.nlabels[] = plt.nlabels[]` doesn't trigger the relabeling of the nodes. Therefore, the changes on the `nlabels` observable appear when another action happens, for example, dragging and dropping nodes. The same code works perfectly when I change the `node_colors` instead of the `node_labels`. 

Code example using GLMakie 0.5.4 and GraphMakie 0.3.3: 

```julia
begin
	using Graphs
	using GLMakie, GraphMakie
end

graph = smallgraph(:karate)

begin
	node_colors = fill(:white, nv(graph))
	node_colors[1] = :lightgray
	node_colors[34] = :lightgray
end

begin
	node_labels = fill("", nv(graph))
	node_labels[1] = "Mr. Hi"
	node_labels[34] = "John A"
end

begin
	figure, axis, plt = graphplot(graph,
		node_color = node_colors,
		node_size = fill(14, nv(graph)),
		node_attr = (strokewidth = 2, strokecolor = :lightgray),
		edge_color = :lightgray,
		edge_width = fill(2, ne(graph)),
		nlabels = node_labels,
		nlabels_align = (:center, :bottom),
		nlabels_distance = 10)
	
	hidespines!(axis)
	hidedecorations!(axis)
	
	figure
end

begin
	deregister_interaction!(axis, :rectanglezoom)
	# register_interaction!(axis, :nhover, NodeHoverHighlight(plt))
	register_interaction!(axis, :ehover, EdgeHoverHighlight(plt))
	register_interaction!(axis, :ndrag, NodeDrag(plt))
	register_interaction!(axis, :edrag, EdgeDrag(plt))
end

function node_action(idx, event, axis)
	if (idx != 1) && (idx != 34)
		if plt.nlabels[][idx] == ""
    		plt.nlabels[][idx] = string(idx)
		else
			plt.nlabels[][idx] = ""
		end
	end
	plt.nlabels[] = plt.nlabels[]
end

register_interaction!(axis, :nodeclick, NodeClickHandler(node_action))

display(figure)
```

Using the following function, the node colors change properly:

```julia
function node_action(idx, event, axis)
	if (idx != 1) && (idx != 34)
		if plt.node_color[][idx] == :white
    		plt.node_color[][idx] = :lightgray
		else
			plt.node_color[][idx] = :white
		end
	end
	plt.node_color[] = plt.node_color[]
end
```

Cheers,

**Comment by hexaeder** [comment]
Interesting, i can reproduce this but I can not explain it. The handling of node color and nlabels internally is quite the same. Simple text plots on their own also react to changes of the text observable. Maybe this is specific to text plots inside other recipes...

**Comment by Cvikli** [comment]
I face with the same problem. What is the best way to solve this problem and having the label updated?

**Comment by Cvikli** [comment]
Maybe worth noting as an avoidant solution I also update the coordinates so it redraw the texts (I guess.

So I added:
`    p.layout[] = p.layout[]`

**Comment by hexaeder** [comment]
seems fixed in current makie versions
