### ISSUE TITLE
use `src(e)` instead of `e.src`

### ISSUE THREAD

**Issue by CarloLucibello** [MakieOrg/GraphMakie.jl#80]
Some code in the librariy, [like this](https://github.com/JuliaPlots/GraphMakie.jl/blob/cb19bae27141c32ded7a5ccafc6461edb69dae10/src/recipes.jl#L333) uses field access on edges, `e.src`, instead of the method `src(e)` which is what is required by Graphs.jl [abstract graph interface](https://juliagraphs.org/Graphs.jl/dev/core_functions/interface/#Graphs.AbstractEdge). 
As a result, `graphplot(g)` on custom graphs with custom edges can produce errors.

**Comment by hexaeder** [comment]
there is a predefined interaction for that allready registered, `ctrl + leftclick`, here in the [Makie docs](https://makie.juliaplots.org/dev/examples/blocks/axis/#limit_reset). If you don't want to use the [rectangle selection zoom](https://makie.juliaplots.org/dev/examples/blocks/axis/#rectangle_selection_zoom) interaction in the first place, you may disable it by
```
fig, ax, p = graphplot(...)
deregister_interaction!(ax, :rectanglezoom)
```
