### ISSUE TITLE
How to add annotations to edges of a SimpleDiGraph?

### ISSUE THREAD

**Issue by shayandavoodii** [MakieOrg/GraphMakie.jl#88]
I have a `SimpleDiGraph` that I want to add the name of each edge on, but I don't know how I can do that. This is my `SimpleDiGraph` plot: <br>

```julia

using Graphs, CairoMakie, GraphMakie

graph = SimpleDiGraph(4)
nodes = ["Q1", "Q2", "Q3", "Q4"]
# edges = [(1, 2), (1, 3), (1, 4), (1, 1), ..., (4, 4)]
for edge in edges
    add_edge!(graph, edge[1], edge[2])
end

graphplot(
    graph,
    names=nodes
)
```
<br>

![image](https://user-images.githubusercontent.com/52105833/189911238-e6d14581-d898-4597-8e7a-5d0f68531c72.png)

Suppose I want to add arbitrary numbers as annotations on edges. How can I do that?

**Comment by hexaeder** [comment]
Interesting, you are loding `GraphMakie` but the plot looks more like a [`GraphRecipes.jl](https://github.com/JuliaPlots/GraphRecipes.jl) plot. Check their documentation for that feature.

In `GraphMakie` there is the `elabels` keyword argument. See the [examples](https://graph.makie.org/stable/generated/plots/#Adding-Edge-Labels) and the [`graphplot` docstring](https://graph.makie.org/previews/PR87/#GraphMakie.graphplot).

**Comment by shayandavoodii** [comment]
Oh, Thanks!<br>Yes, My bad 😅. This mistake is because I had imported many packages into my environment, so I didn't realize I had been using which `graphplot`, The one that relates to `GraphRecipes` or `GraphMakie`.
