### ISSUE TITLE
Unable to make animation using GraphMakie

### ISSUE THREAD

**Issue by TorkelE** [MakieOrg/GraphMakie.jl#90]
I want to create a simple animation where the colour of the nodes in a graph change. I have tried adapting the Makie animation tutorial, but it does not seem to work for graphs. This is the example:
```julia
# Fetch packages
using Pkg; Pkg.activate(".");
using Makie
using GLMakie
using GraphMakie
using Graphs
using Makie.Colors

# Create a line animation, where the line's color changes (works).
fig_line, ax_line, plot_line = lines(0..10, sin; linewidth=10)
function change_function_line(frame)
    plot_line.color = HSV(frame, 1, 0.75)
end
record(change_function_line, fig_line, "color_animation_line.mp4", range(0,360, length=30); framerate=3)


# Create a graph animation, where the graphs's color changes (does not work, the colors stay static throughout the animation).
fig_graph, ax_graph, plot_graph = GraphMakie.graphplot(path_graph(10),node_color=rand(RGB,10),node_size=40,edge_size=1)
function change_function_graph(frame)
    plot_graph.node_color[][:] = rand(RGB,10)
end
record(change_function_graph, fig_graph, "color_animation_graph.mp4", range(0,360, length=30); framerate=3)

# Check whenever changing graph color is possible:
fig_graph                                   # Check the colors of the graph.
plot_graph.node_color[][:] = rand(RGB,10);  # Chanegs the colors of the graph.
fig_graph                                   # Check the colors of the graph. It is different.
```

I am also uploading the two animations:
https://user-images.githubusercontent.com/18099310/191730460-bcd88fec-4194-44a2-8552-6df4db56ce02.mp4
https://user-images.githubusercontent.com/18099310/191730463-b6621331-9f39-4a3a-a492-eea4ad357a33.mp4
And the graph before and after I change its colour:
![image](https://user-images.githubusercontent.com/18099310/191730598-a31e744b-7371-46f8-a055-496b51e8f459.png)
![image](https://user-images.githubusercontent.com/18099310/191730734-bca8348a-be89-4695-845a-de3c552bc006.png)

**Comment by SimonDanisch** [comment]
Because `plot_graph.node_color[][:] = rand(RGB,10)` that just changes the array without updating the observable.
Add `notify(plot_graph.node_color)`, or do `plot_graph.node_color = rand(RGB,10)` (preferred, if you don't have a good reason).

**Comment by TorkelE** [comment]
Thanks!
