### ISSUE TITLE
plot at the bottom of https://graph.makie.org/stable/generated/plots/ doesn't seem to render correctly

### ISSUE THREAD

**Issue by anandijain** [MakieOrg/GraphMakie.jl#96]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/33790004/207702465-ca0d7a30-966a-4b2c-9a42-7351f786c78d.png">

it renders right initially, but any interaction seems to break

**Comment by hexaeder** [comment]
Yeah i think this is some problem with WGLMakie with JServed backend. I would guess it is not graphmakie specific but will happen with every 3d scatter plot. I think the best thing would be to create a pure Makie MWE and raise an issue there...

**Comment by hexaeder** [comment]
fixed in new version WGLMakie/JSServe
