### ISSUE TITLE
Problems plotting directed graphs without edges

### ISSUE THREAD

**Issue by lmshk** [MakieOrg/GraphMakie.jl#97]
On Julia v1.8.3 with GraphMakie **v0.4.3**, Makie v0.18.2, GLMakie v0.7.2 and:

```julia
using GLMakie, GraphMakie; import Graphs
graph = Graphs.SimpleDiGraph(2)
```

the following work as expected:

```julia
graphplot(graph)
graphplot(graph, edge_plottype = Makie.automatic)
```

while these do not:

```julia
graphplot(graph, edge_plottype = :linesegments)
# ERROR: MethodError: no method matching ptype(::Type{Any})

# (this is the one I actually need:)
graphplot(graph, edge_plottype = :beziersegments)
# ERROR: StackOverflowError:
# [...]
# Billboard(angles::Vector{Any}) (repeats 15393 times)
#    @ MakieCore ~/.julia/packages/MakieCore/77C6Z/src/types.jl:112
```

I can work around this by conditionally setting `edge_plottype = Makie.automatic` if the graph has no edges.

(Slightly off-topic, but `graphplot(graph, edge_plottype = :somethingelse)` gives a confusing error message `MethodError: no method matching length(::Nothing)` while it should probably complain about an invalid plot type instead.)

**Comment by lmshk** [comment]
The problem also occurs on Julia v1.8.3 with GraphMakie **v0.5.0**, Makie v0.19.0 and GLMakie v0.8.0.

**Comment by hexaeder** [comment]
Hm the error message should be improved i agree. I'll try to look into the problem the next days. Just out of curiosity: What are you trying to do with beziersegments which isn't covered using automatic mode?

**Comment by lmshk** [comment]
See #93.
